CREATE TABLE NEWS
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    Title      TEXT,
    Content    TEXT,
    Url        VARCHAR(2000),
    Created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    Updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE LINKS_UN_HANDLED
(
    id   BIGINT PRIMARY KEY AUTO_INCREMENT,
    link VARCHAR(2000)
);

CREATE TABLE LINKS_IN_HANDLED
(
    id   BIGINT PRIMARY KEY AUTO_INCREMENT,
    link VARCHAR(2000)
);

INSERT INTO LINKS_UN_HANDLED(LINK)
VALUES ('https://sina.cn')

