MODNAME		?= myhook

obj-m		+= $(MODNAME).o
$(MODNAME)-y	+= hook_openat.o

ccflags-y	+= -Werror -fno-stack-protector -fomit-frame-pointer
ldflags-y	+= -T$(src)/khook/engine.lds # use LDFLAGS for old kernels

KBUILD_CFLAGS	:= $(filter-out -pg,$(KBUILD_CFLAGS))
KBUILD_CFLAGS	:= $(filter-out -mfentry,$(KBUILD_CFLAGS))
